'use client';
import React, { useState, useEffect, useRef } from 'react';
import { useReactFlow, MarkerType, type Node, type Edge } from '@xyflow/react';
import { ProcessorProps } from './types';
import { BookOpen, Sparkles, Plus, TrendingUp, Clock, Target } from 'lucide-react';

export default function CourseProcessor({ node }: ProcessorProps) {
    const [isGenerating, setIsGenerating] = useState(false);
    const [isArchitecting, setIsArchitecting] = useState(false);
    const { setNodes, setEdges, getNodes, getEdges } = useReactFlow();

    if (!node || node.type !== 'courseNode') return null;

    const metadata = node.data?.metadata as Record<string, any> | undefined;
    const courseData = metadata?.courseData || {};
    const modules = courseData.modules || [];
    const masteryLevel = metadata?.masteryLevel || 0;
    const sourceContent = metadata?.sourceContent || node.data?.content;
    const hasAutoGenerated = useRef(false);

    // Auto-generate course from source content when node is created
    useEffect(() => {
        // 1. If we have source content, trigger generation
        if (sourceContent && modules.length === 0 && !hasAutoGenerated.current && !isArchitecting) {
            hasAutoGenerated.current = true;
            generateCourse(sourceContent);
        }
        // 2. If NO source content, look for connected nodes (Note, Doc, etc.)
        else if (!sourceContent && modules.length === 0) {
            const edges = getEdges();
            const nodes = getNodes();
            const inputEdge = edges.find(e => e.target === node.id);
            if (inputEdge) {
                const sourceNode = nodes.find(n => n.id === inputEdge.source);
                const metadata = sourceNode?.data?.metadata as Record<string, any> | undefined;
                const content = sourceNode?.data?.content || metadata?.raw_content;

                if (sourceNode && content && typeof content === 'string') {
                    console.log('[CourseProcessor] Found connected source:', sourceNode.id);
                    // Update metadata with sourceContent to trigger the block above on next render
                    setNodes(nds => nds.map(n => n.id === node.id ? {
                        ...n,
                        data: {
                            ...n.data,
                            metadata: {
                                ...(typeof n.data.metadata === 'object' ? n.data.metadata : {}),
                                sourceContent: content
                            }
                        }
                    } : n));
                }
            }
        }
    }, [sourceContent, modules.length, isArchitecting, node, setNodes, getEdges, getNodes]);

    // Study Mode State
    const initialTab = metadata?.activeTab === 'study' ? 'study' : 'structure';
    const [activeTab, setActiveTabState] = useState<'structure' | 'study'>(initialTab);
    const [chatHistory, setChatHistory] = useState<any[]>([]);
    const [userQuery, setUserQuery] = useState('');
    const [isThinking, setIsThinking] = useState(false);
    const [studyFocus, setStudyFocus] = useState<string | null>(null);

    // Sync local state with metadata changes (e.g. from Canvas node button)
    useEffect(() => {
        if (metadata?.activeTab && metadata.activeTab !== activeTab) {
            setActiveTabState(metadata.activeTab);
        }
    }, [metadata?.activeTab]);

    const setActiveTab = (tab: 'structure' | 'study') => {
        setActiveTabState(tab);
        // Persist to metadata
        setNodes(nds => nds.map(n => n.id === node.id ? {
            ...n,
            data: {
                ...n.data,
                metadata: {
                    ...(typeof n.data.metadata === 'object' ? n.data.metadata : {}),
                    activeTab: tab
                }
            }
        } : n));
    };

    const handleAskTutor = async (query?: string) => {
        const prompt = query || userQuery;
        if (!prompt.trim()) return;

        // Add user message immediately
        const newHistory = [...chatHistory, { role: 'user', content: prompt }];
        setChatHistory(newHistory);
        setUserQuery('');
        setIsThinking(true);

        try {
            // DYNAMIC CONTEXT FETCHING
            // 1. Get explicit sourceContent from metadata
            let contextContent = sourceContent || '';

            // 2. If empty, or just to be safe, look for connected nodes dynamically
            const allEdges = getEdges();
            const allNodes = getNodes();
            const connectedEdges = allEdges.filter(e => e.target === node.id || e.source === node.id);

            const connectedContexts = connectedEdges.map(edge => {
                const otherId = edge.source === node.id ? edge.target : edge.source;
                const otherNode = allNodes.find(n => n.id === otherId);
                if (!otherNode) return '';

                const metadata = otherNode.data.metadata as Record<string, any> | undefined;
                // Extract text from various node types
                const content = otherNode.data.content
                    || metadata?.raw_content
                    || metadata?.summary
                    || '';

                return content ? `[Connected Node: ${otherNode.data.label || otherNode.type}]\n${content.substring(0, 5000)}` : '';
            }).filter(Boolean).join('\n\n');

            if (connectedContexts) {
                contextContent += `\n\n=== CONNECTED KNOWLEDGE ===\n${connectedContexts}`;
            }

            // Build final context
            let context = `COURSE: ${node.data.label}\nSOURCE MATERIAL:\n${contextContent || 'No source content provided.'}`;

            if (studyFocus) {
                const module = modules.find((m: any) => m.title === studyFocus);
                if (module) {
                    context += `\n\nFOCUS MODULE: ${module.title}\nCORE IDEA: ${module.coreIdea}\nTOPICS: ${module.subTopics?.join(', ')}`;
                }
            }

            const response = await fetch('/api/agents/tutor', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'chat',
                    context: context,
                    userPrompt: prompt,
                    history: newHistory.slice(-4) // Send last few messages for context
                })
            });

            const data = await response.json();
            if (data.success) {
                setChatHistory([...newHistory, { role: 'assistant', content: data.reply }]);
            }
        } catch (error) {
            console.error('Tutor Error:', error);
            setChatHistory([...newHistory, { role: 'assistant', content: 'Connection input error. Please try again.' }]);
        } finally {
            setIsThinking(false);
        }
    };

    const generateCourse = async (content: string) => {
        setIsArchitecting(true);
        try {
            const response = await fetch('/api/agents/course', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    nodes: [{ ...node, data: { ...node.data, content: content } }],
                    userPrompt: `Create a comprehensive learning course from this content: ${content.substring(0, 500)}...`
                })
            });

            const result = await response.json();

            if (result.success) {
                const generatedCourseData = result.result.metadata;

                setNodes((nds) =>
                    nds.map((n) => {
                        if (n.id !== node.id) return n;
                        const existingMetadata = typeof n.data.metadata === 'object' && n.data.metadata !== null
                            ? n.data.metadata as Record<string, any>
                            : {};
                        return {
                            ...n,
                            data: {
                                ...n.data,
                                label: generatedCourseData.courseTitle || n.data.label,
                                metadata: {
                                    ...existingMetadata,
                                    courseData: generatedCourseData,
                                    masteryLevel: 0,
                                    sourceContent: undefined, // Clear to prevent re-triggering
                                },
                            },
                        };
                    })
                );
            }
        } catch (error) {
            console.error('[CourseProcessor] Auto-generation error:', error);
        } finally {
            setIsArchitecting(false);
        }
    };

    const handleGenerateQuiz = async () => {
        console.log('[CourseProcessor] Generate Quiz clicked');
        setIsGenerating(true);
        try {
            console.log('[CourseProcessor] Calling Quiz Master API with node:', node.id, node.data?.label);

            // Call Quiz Master agent
            const response = await fetch('/api/agents/quiz', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    nodes: [node],
                    userPrompt: `Generate a comprehensive quiz for the course: ${node.data.label}`
                })
            });

            console.log('[CourseProcessor] API response status:', response.status);
            const result = await response.json();
            console.log('[CourseProcessor] API result:', result);

            if (result.success) {
                const quizData = result.result.metadata;
                const questionCount = quizData.questions?.length || 0;

                // Check if a quiz node already exists connected to this course
                const allNodes = getNodes();
                const allEdges = getEdges();

                const existingQuizNode = allNodes.find((n) => {
                    // Find quiz nodes connected to this course node
                    const hasEdge = allEdges.some((e) =>
                        (e.source === node.id && e.target === n.id && n.type === 'quizNode') ||
                        (e.target === node.id && e.source === n.id && n.type === 'quizNode')
                    );
                    return hasEdge;
                });

                if (existingQuizNode) {
                    // Update existing quiz node
                    console.log('[CourseProcessor] Updating existing quiz node:', existingQuizNode.id);
                    setNodes((nds) =>
                        nds.map((n) => {
                            if (n.id !== existingQuizNode.id) return n;
                            const existingMetadata = typeof n.data.metadata === 'object' && n.data.metadata !== null
                                ? n.data.metadata as Record<string, any>
                                : {};
                            return {
                                ...n,
                                data: {
                                    ...n.data,
                                    label: `${node.data.label} Quiz`,
                                    metadata: {
                                        ...existingMetadata,
                                        quizData: quizData,
                                        performance: existingMetadata.performance || { attempts: 0, correct: 0, incorrect: 0 }
                                    },
                                },
                            };
                        })
                    );
                } else {
                    // Create new quiz node below the course node
                    console.log('[CourseProcessor] Creating new quiz node');
                    const newQuizNode: Node = {
                        id: `quizNode-${Date.now()}`,
                        type: 'quizNode',
                        position: { x: node.position.x, y: node.position.y + 250 },
                        data: {
                            label: `${node.data.label} Quiz`,
                            metadata: {
                                quizData: quizData,
                                performance: { attempts: 0, correct: 0, incorrect: 0 }
                            },
                        },
                    };

                    // Create edge connecting course to quiz
                    const newEdge: Edge = {
                        id: `edge-${node.id}-${newQuizNode.id}`,
                        source: node.id,
                        target: newQuizNode.id,
                        type: 'default',
                        markerEnd: { type: MarkerType.ArrowClosed },
                        animated: true,
                        style: { stroke: '#3b82f6' } // Blue edge for course-quiz connection
                    };

                    setNodes((nds) => nds.concat(newQuizNode));
                    setEdges((eds) => eds.concat(newEdge));
                }

                alert(`Quiz generated! ${questionCount} questions created.`);
            } else {
                alert('Failed to generate quiz: ' + result.error);
            }
        } catch (error: any) {
            console.error('[CourseProcessor] Error:', error);
            alert('Error: ' + error.message);
        } finally {
            console.log('[CourseProcessor] Setting isGenerating to false');
            setIsGenerating(false);
        }
    };

    const handleAddMaterials = async () => {
        setIsArchitecting(true);
        try {
            // Call Course Architect agent
            const response = await fetch('/api/agents/course', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    nodes: [node],
                    userPrompt: `Structure the materials in "${node.data.label}" into a comprehensive learning path`
                })
            });

            const result = await response.json();

            if (result.success) {
                const courseData = result.result.metadata;

                // Update the node with the generated course data
                setNodes((nds) =>
                    nds.map((n) => {
                        if (n.id !== node.id) return n;
                        const existingMetadata = typeof n.data.metadata === 'object' && n.data.metadata !== null
                            ? n.data.metadata as Record<string, any>
                            : {};
                        return {
                            ...n,
                            data: {
                                ...n.data,
                                label: courseData.courseTitle || n.data.label,
                                metadata: {
                                    ...existingMetadata,
                                    courseData: courseData,
                                    masteryLevel: 0,
                                },
                            },
                        };
                    })
                );

                alert(`Course structured! ${courseData.modules?.length || 0} modules created:\n${courseData.courseTitle}`);
            } else {
                alert('Failed to structure course: ' + result.error);
            }
        } catch (error: any) {
            alert('Error: ' + error.message);
        } finally {
            setIsArchitecting(false);
        }
    };

    return (
        <div className="flex flex-col h-full animate-in fade-in duration-500">
            {/* Header / Tabs */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2 text-xs text-slate-500 font-bold uppercase tracking-wider">
                    <BookOpen className="w-3 h-3 text-purple-400" />
                    Course Architect
                </div>
                <div className="flex bg-slate-900 rounded-lg p-0.5 border border-slate-800">
                    <button
                        onClick={() => setActiveTab('structure')}
                        className={`px-3 py-1 text-[10px] font-bold rounded transition-colors ${activeTab === 'structure' ? 'bg-purple-600 text-white' : 'text-slate-400 hover:text-slate-300'}`}
                    >
                        Structure
                    </button>
                    <button
                        onClick={() => setActiveTab('study')}
                        className={`px-3 py-1 text-[10px] font-bold rounded transition-colors ${activeTab === 'study' ? 'bg-emerald-600 text-white' : 'text-slate-400 hover:text-slate-300'}`}
                    >
                        Deep Dive
                    </button>
                </div>
            </div>

            {/* MAIN CONTENT AREA */}
            <div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar pr-1">
                {activeTab === 'structure' ? (
                    // STRUCTURE VIEW
                    <div className="space-y-4">
                        {/* Source Content Input */}
                        <div className="space-y-2">
                            <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                                <TrendingUp className="w-3 h-3" />
                                Source Material
                            </label>
                            <textarea
                                value={sourceContent}
                                onChange={(e) => {
                                    const newContent = e.target.value;
                                    setNodes(nds => nds.map(n => n.id === node.id ? {
                                        ...n,
                                        data: { ...n.data, metadata: { ...metadata, sourceContent: newContent } }
                                    } : n));
                                }}
                                placeholder="Paste raw notes, transcripts, or book summaries here..."
                                className="w-full h-24 bg-slate-900 border border-slate-800 rounded-lg p-3 text-xs text-slate-300 placeholder:text-slate-600 resize-none focus:outline-none focus:border-purple-500/50 transition-all custom-scrollbar"
                            />
                        </div>

                        {/* Modules List */}
                        <div className="space-y-2">
                            <div className="flex items-center justify-between">
                                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                                    <BookOpen className="w-3 h-3" />
                                    Curriculum ({modules.length})
                                </label>
                                {modules.length > 0 && (
                                    <button
                                        onClick={() => {
                                            setNodes(nds => nds.map(n => n.id === node.id ? {
                                                ...n,
                                                data: { ...n.data, metadata: { ...metadata, courseData: { ...courseData, modules: [] } } }
                                            } : n));
                                            hasAutoGenerated.current = false;
                                        }}
                                        className="text-[10px] text-red-400 hover:text-red-300 transition-colors"
                                    >
                                        Clear
                                    </button>
                                )}
                            </div>

                            <div className="space-y-3">
                                {modules.map((module: any, idx: number) => (
                                    <div key={idx} className="bg-slate-900/50 border border-slate-800 rounded-lg p-3 hover:border-purple-500/30 transition-colors group">
                                        <div className="flex items-start gap-2">
                                            <div className="w-6 h-6 rounded bg-purple-500/20 flex items-center justify-center flex-shrink-0">
                                                <span className="text-xs font-bold text-purple-400">{module.moduleNumber}</span>
                                            </div>
                                            <div className="flex-1 min-w-0">
                                                <div className="text-xs font-semibold text-slate-200 mb-1">{module.title}</div>
                                                <div className="text-[10px] text-slate-500 mb-2">{module.coreIdea}</div>
                                                <div className="flex flex-wrap gap-1 mb-2">
                                                    {module.subTopics?.slice(0, 3).map((topic: string, i: number) => (
                                                        <span key={i} className="text-[9px] px-2 py-0.5 bg-slate-800 text-slate-400 rounded-full">
                                                            {topic}
                                                        </span>
                                                    ))}
                                                </div>
                                                <div className="flex gap-2 opacity-100 sm:opacity-0 sm:group-hover:opacity-100 transition-opacity">
                                                    <button
                                                        onClick={(e) => {
                                                            e.stopPropagation();
                                                            setStudyFocus(module.title);
                                                            setActiveTab('study');
                                                            setChatHistory([{ role: 'assistant', content: `Ready to deep dive into **${module.title}**! Ask me anything about ${module.coreIdea}.` }]);
                                                        }}
                                                        className="flex-1 flex items-center justify-center gap-1.5 py-1.5 bg-emerald-900/20 hover:bg-emerald-900/40 text-emerald-400 rounded text-[10px] font-medium transition-colors border border-emerald-700/30"
                                                    >
                                                        <BookOpen className="w-3 h-3" />
                                                        Study
                                                    </button>
                                                    <button
                                                        onClick={(e) => {
                                                            e.stopPropagation();
                                                            const event = new CustomEvent('createNoteFromContent', {
                                                                detail: {
                                                                    sourceNodeId: node.id,
                                                                    content: `# ${module.title}\n\n**Core Idea:** ${module.coreIdea}\n\n## Key Topics\n${module.subTopics?.map((t: string) => `- ${t}`).join('\n')}\n\n## Lesson Content\n[Use the Writing Agent to expand this...]`,
                                                                    label: `Lesson: ${module.title}`
                                                                }
                                                            });
                                                            window.dispatchEvent(event);
                                                        }}
                                                        className="flex-1 flex items-center justify-center gap-1.5 py-1.5 bg-purple-900/20 hover:bg-purple-900/40 text-purple-400 rounded text-[10px] font-medium transition-colors border border-purple-700/30"
                                                    >
                                                        <Sparkles className="w-3 h-3" />
                                                        Write
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Generate Button Area */}
                        <div className="pt-2">
                            <button
                                onClick={handleAddMaterials}
                                disabled={isArchitecting || !sourceContent}
                                className="w-full py-2 bg-slate-800 hover:bg-purple-900/20 border border-slate-700 hover:border-purple-500/50 rounded-lg text-slate-300 hover:text-purple-300 text-xs font-bold uppercase transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {isArchitecting ? (
                                    <>
                                        <Sparkles className="w-3 h-3 animate-spin" />
                                        Architecting...
                                    </>
                                ) : (
                                    <>
                                        <Plus className="w-3 h-3" />
                                        {modules.length === 0 ? 'Generate Structure' : 'Regenerate Structure'}
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                ) : (
                    // STUDY VIEW
                    <div className="flex flex-col h-full bg-slate-950 rounded-lg border border-slate-800 overflow-hidden">
                        {/* Chat Header */}
                        {studyFocus && (
                            <div className="bg-emerald-900/20 border-b border-emerald-900/30 p-2 flex items-center justify-between">
                                <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider truncate">
                                    Focus: {studyFocus}
                                </span>
                                <button onClick={() => setStudyFocus(null)} className="text-slate-500 hover:text-slate-300">
                                    <Target className="w-3 h-3" />
                                </button>
                            </div>
                        )}

                        {/* Messages Area */}
                        <div className="flex-1 overflow-y-auto p-3 space-y-3 custom-scrollbar">
                            {chatHistory.length === 0 && (
                                <div className="text-center text-slate-600 mt-10">
                                    <BookOpen className="w-8 h-8 mx-auto mb-2 opacity-20" />
                                    <p className="text-xs">Ask anything about the course material.</p>
                                    <p className="text-[10px] mt-1">"Explain the core concept"</p>
                                    <p className="text-[10px]">"Quiz me on Module 1"</p>
                                </div>
                            )}
                            {chatHistory.map((msg, idx) => (
                                <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                    <div className={`max-w-[85%] rounded-lg p-2.5 text-xs leading-relaxed ${msg.role === 'user'
                                        ? 'bg-emerald-600 text-white'
                                        : 'bg-slate-800 text-slate-300 border border-slate-700'
                                        }`}>
                                        <div className="whitespace-pre-wrap">{msg.content}</div>
                                    </div>
                                </div>
                            ))}
                            {isThinking && (
                                <div className="flex justify-start">
                                    <div className="bg-slate-800 rounded-lg p-2.5 border border-slate-700">
                                        <Sparkles className="w-3 h-3 text-emerald-400 animate-spin" />
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Input Area */}
                        <div className="p-2 bg-slate-900 border-t border-slate-800">
                            <div className="relative">
                                <textarea
                                    value={userQuery}
                                    onChange={(e) => setUserQuery(e.target.value)}
                                    onKeyDown={(e) => {
                                        if (e.key === 'Enter' && !e.shiftKey) {
                                            e.preventDefault();
                                            handleAskTutor();
                                        }
                                    }}
                                    placeholder="Ask a question..."
                                    className="w-full bg-slate-950 border border-slate-700 rounded-lg pl-3 pr-10 py-2 text-xs text-slate-200 focus:outline-none focus:border-emerald-500 resize-none h-10 custom-scrollbar"
                                />
                                <button
                                    onClick={() => handleAskTutor()}
                                    disabled={!userQuery.trim() || isThinking}
                                    className="absolute right-1.5 top-1.5 p-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded transition-colors disabled:opacity-50"
                                >
                                    <Target className="w-3 h-3" />
                                </button>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
