'use client';
import React, { useState, useEffect, useRef } from 'react';
import { ProcessorProps } from './types';
import { HelpCircle, CheckCircle, XCircle, Award, RotateCw, Sparkles } from 'lucide-react';

export default function QuizProcessor({ node }: ProcessorProps) {
    const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
    const [userAnswers, setUserAnswers] = useState<Record<string, any>>({});
    const [showResults, setShowResults] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);

    if (!node || node.type !== 'quizNode') return null;

    const metadata = typeof node.data?.metadata === 'object' && node.data?.metadata !== null
        ? node.data.metadata as Record<string, any>
        : {};
    const quizData = metadata.quizData || {};
    const questions = quizData.questions || [];
    const performance = metadata.performance || { attempts: 0, correct: 0, incorrect: 0 };
    const sourceContent = metadata?.sourceContent || node.data?.content;
    const hasAutoGenerated = useRef(false);
    const [isGenerating, setIsGenerating] = useState(false);

    // Auto-generate quiz from source content when node is created
    useEffect(() => {
        if (sourceContent && questions.length === 0 && !hasAutoGenerated.current && !isGenerating) {
            hasAutoGenerated.current = true;
            (async () => {
                setIsGenerating(true);
                try {
                    const response = await fetch('/api/agents/quiz', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                            nodes: [{ ...node, data: { ...node.data, content: sourceContent } }],
                            userPrompt: `Generate a comprehensive quiz to test knowledge of this content: ${sourceContent.substring(0, 500)}...`
                        })
                    });

                    const result = await response.json();

                    if (result.success && typeof window !== 'undefined') {
                        const generatedQuizData = result.result.metadata;
                        // Update node via custom event
                        const event = new CustomEvent('updateQuizNode', {
                            detail: {
                                nodeId: node.id,
                                quizData: generatedQuizData,
                                clearSource: true
                            }
                        });
                        window.dispatchEvent(event);
                    }
                } catch (error) {
                    console.error('[QuizProcessor] Auto-generation error:', error);
                } finally {
                    setIsGenerating(false);
                }
            })();
        }
    }, [sourceContent, questions.length, isGenerating, node]);

    // Show generating state
    if (isGenerating) {
        return (
            <div className="p-8 text-center">
                <Sparkles className="w-12 h-12 text-blue-400 mx-auto mb-3 animate-pulse" />
                <div className="text-sm text-slate-300 font-semibold">Generating Quiz...</div>
                <div className="text-xs text-slate-500 mt-2">AI is creating questions from your content</div>
            </div>
        );
    }

    if (questions.length === 0) {
        return (
            <div className="p-8 text-center">
                <HelpCircle className="w-12 h-12 text-slate-600 mx-auto mb-3" />
                <div className="text-sm text-slate-400">No questions available</div>
            </div>
        );
    }

    const currentQuestion = questions[currentQuestionIndex];
    const totalQuestions = questions.length;
    const isLastQuestion = currentQuestionIndex === totalQuestions - 1;

    const handleAnswer = (answer: any) => {
        setUserAnswers({
            ...userAnswers,
            [currentQuestion.id]: answer
        });
    };

    const handleNext = () => {
        if (isLastQuestion) {
            setShowResults(true);
        } else {
            setCurrentQuestionIndex(currentQuestionIndex + 1);
        }
    };

    const handlePrevious = () => {
        if (currentQuestionIndex > 0) {
            setCurrentQuestionIndex(currentQuestionIndex - 1);
        }
    };

    const handleSubmit = async () => {
        setIsSubmitting(true);

        // Calculate score
        let correct = 0;
        let incorrect = 0;

        questions.forEach((q: any) => {
            const userAnswer = userAnswers[q.id];
            if (userAnswer && userAnswer.toLowerCase().trim() === q.correctAnswer.toLowerCase().trim()) {
                correct++;
            } else {
                incorrect++;
            }
        });

        const scorePercentage = Math.round((correct / totalQuestions) * 100);

        // Update node metadata with performance
        const updatedPerformance = {
            attempts: performance.attempts + 1,
            correct: correct,
            incorrect: incorrect,
            lastScore: scorePercentage,
            lastAttemptDate: new Date().toISOString()
        };

        // Update React Flow nodes
        if (typeof window !== 'undefined') {
            const event = new CustomEvent('updateQuizNode', {
                detail: {
                    nodeId: node.id,
                    performance: updatedPerformance
                }
            });
            window.dispatchEvent(event);
        }

        alert(`Quiz Complete!\n\nScore: ${scorePercentage}%\n${correct}/${totalQuestions} correct`);

        setIsSubmitting(false);
        setShowResults(false);
        setCurrentQuestionIndex(0);
        setUserAnswers({});
    };

    const handleRestart = () => {
        setShowResults(false);
        setCurrentQuestionIndex(0);
        setUserAnswers({});
    };

    if (showResults) {
        const answeredCount = Object.keys(userAnswers).length;
        return (
            <div className="animate-in fade-in duration-500 space-y-4">
                <div className="text-center p-6">
                    <Award className="w-16 h-16 text-blue-400 mx-auto mb-4" />
                    <div className="text-xl font-bold text-slate-200 mb-2">Review Your Answers</div>
                    <div className="text-sm text-slate-400">
                        {answeredCount}/{totalQuestions} questions answered
                    </div>
                </div>

                <div className="space-y-3 max-h-64 overflow-y-auto custom-scrollbar">
                    {questions.map((q: any, idx: number) => {
                        const userAnswer = userAnswers[q.id];
                        const isCorrect = userAnswer?.toLowerCase().trim() === q.correctAnswer.toLowerCase().trim();
                        const isAnswered = userAnswer !== undefined;

                        return (
                            <div key={q.id} className={`p-3 rounded-lg border ${!isAnswered ? 'bg-slate-900 border-slate-800' :
                                isCorrect ? 'bg-green-900/20 border-green-500/30' : 'bg-red-900/20 border-red-500/30'
                                }`}>
                                <div className="flex items-start gap-2">
                                    <div className="w-5 h-5 flex-shrink-0">
                                        {!isAnswered ? (
                                            <div className="w-5 h-5 rounded-full bg-slate-800 text-slate-600 flex items-center justify-center text-[10px] font-bold">
                                                {idx + 1}
                                            </div>
                                        ) : isCorrect ? (
                                            <CheckCircle className="w-5 h-5 text-green-400" />
                                        ) : (
                                            <XCircle className="w-5 h-5 text-red-400" />
                                        )}
                                    </div>
                                    <div className="flex-1 text-xs text-slate-300">
                                        <div className="font-semibold mb-1">{q.question}</div>
                                        {isAnswered && (
                                            <div className="text-[10px] text-slate-500">
                                                Your answer: <span className={isCorrect ? 'text-green-400' : 'text-red-400'}>{userAnswer}</span>
                                                {!isCorrect && <div className="text-blue-400 mt-1">Correct: {q.correctAnswer}</div>}
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>
                        );
                    })}
                </div>

                <div className="flex gap-2 pt-4 border-t border-slate-800">
                    <button
                        onClick={handleRestart}
                        className="flex-1 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-400 rounded-lg text-sm transition-colors flex items-center justify-center gap-2"
                    >
                        <RotateCw className="w-4 h-4" />
                        Retake
                    </button>
                    <button
                        onClick={handleSubmit}
                        disabled={answeredCount < totalQuestions || isSubmitting}
                        className="flex-1 px-4 py-2 bg-blue-500/20 hover:bg-blue-500/30 disabled:bg-slate-900 disabled:text-slate-600 text-blue-400 rounded-lg text-sm font-semibold transition-colors"
                    >
                        {isSubmitting ? 'Submitting...' : 'Submit Quiz'}
                    </button>
                </div>
            </div>
        );
    }

    const userAnswer = userAnswers[currentQuestion.id];

    return (
        <div className="animate-in fade-in duration-500 space-y-4">
            {/* Progress */}
            <div className="flex items-center justify-between text-xs mb-4">
                <span className="text-slate-500">Question {currentQuestionIndex + 1} of {totalQuestions}</span>
                <span className="text-blue-400 font-semibold">{Math.round(((currentQuestionIndex + 1) / totalQuestions) * 100)}%</span>
            </div>

            <div className="h-1 bg-slate-800 rounded-full overflow-hidden mb-6">
                <div
                    className="h-full bg-blue-500 transition-all duration-300"
                    style={{ width: `${((currentQuestionIndex + 1) / totalQuestions) * 100}%` }}
                />
            </div>

            {/* Question */}
            <div className="p-4 bg-slate-900 rounded-lg border border-slate-800">
                <div className="flex items-start gap-2 mb-4">
                    <HelpCircle className="w-5 h-5 text-blue-400 flex-shrink-0 mt-0.5" />
                    <div className="text-sm text-slate-200 font-medium">{currentQuestion.question}</div>
                </div>

                {/* Difficulty Badge */}
                <div className="inline-block px-2 py-1 rounded text-[10px] font-semibold mb-3" style={{
                    backgroundColor: currentQuestion.difficulty === 'basic' ? '#1e3a8a20' :
                        currentQuestion.difficulty === 'intermediate' ? '#78350f20' : '#7e22ce20',
                    color: currentQuestion.difficulty === 'basic' ? '#60a5fa' :
                        currentQuestion.difficulty === 'intermediate' ? '#fb923c' : '#c084fc'
                }}>
                    {currentQuestion.difficulty}
                </div>

                {/* Answer Input based on type */}
                {currentQuestion.type === 'multiple_choice' && (
                    <div className="space-y-2">
                        {currentQuestion.options.map((option: string, idx: number) => (
                            <button
                                key={idx}
                                onClick={() => handleAnswer(option)}
                                className={`w-full p-3 rounded-lg border text-left text-sm transition-all ${userAnswer === option
                                    ? 'bg-blue-500/20 border-blue-500/50 text-blue-300'
                                    : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-blue-500/30'
                                    }`}
                            >
                                <span className="font-mono text-blue-400 mr-2">{String.fromCharCode(65 + idx)}.</span>
                                {option}
                            </button>
                        ))}
                    </div>
                )}

                {currentQuestion.type === 'fill_in_blank' && (
                    <input
                        type="text"
                        value={userAnswer || ''}
                        onChange={(e) => handleAnswer(e.target.value)}
                        placeholder="Type your answer..."
                        className="w-full p-3 bg-slate-800 border border-slate-700 rounded-lg text-sm text-slate-200 focus:border-blue-500/50 focus:outline-none"
                    />
                )}

                {currentQuestion.type === 'open_ended' && (
                    <textarea
                        value={userAnswer || ''}
                        onChange={(e) => handleAnswer(e.target.value)}
                        placeholder="Write your detailed answer..."
                        rows={4}
                        className="w-full p-3 bg-slate-800 border border-slate-700 rounded-lg text-sm text-slate-200 focus:border-blue-500/50 focus:outline-none resize-none"
                    />
                )}
            </div>

            {/* Navigation */}
            <div className="flex gap-2">
                <button
                    onClick={handlePrevious}
                    disabled={currentQuestionIndex === 0}
                    className="px-4 py-2 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed text-slate-400 rounded-lg text-sm transition-colors"
                >
                    Previous
                </button>
                <button
                    onClick={handleNext}
                    disabled={!userAnswer}
                    className="flex-1 px-4 py-2 bg-blue-500/20 hover:bg-blue-500/30 disabled:bg-slate-900 disabled:text-slate-600 text-blue-400 rounded-lg text-sm font-semibold transition-colors"
                >
                    {isLastQuestion ? 'Review Answers' : 'Next Question'}
                </button>
            </div>
        </div>
    );
}
